name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container Registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.HEROKU_USERNAME }}
          password: ${{ secrets.HEROKU_API_KEY }}
          repository: registry.heroku.com/yeah/web
          tag_with_sha: true
      - name: Deploy to Heroku
        run: |
          heroku container:release web -a yeah
